AllCops:
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'config/initializers/pluralization.rb'
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/EndOfLine:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true

Style/ExpandPathArguments:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Style/RedundantConstantBase:
  Enabled: true

Lint/EmptyBlock:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  CountComments: false
  Max: 25

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false
